### ISSUE TITLE
compatibility with 2.0.0-alpha.22 

### ISSUE THREAD

**Issue by maku** [auth0/angular2-authentication-sample#13]
The project is not compatible with 2.0.0-alpha.22, right?
Any plans to update?

**Comment by PatrickJS** [comment]
Yup, as soon as I get back home (at the airport atm)

**Comment by maku** [comment]
Cool, thx!

**Comment by mgonto** [comment]
It'll keep on breaking with newer updates, that's what happens with Bleeding edge :D. We'll update it as often as we can though.
