### ISSUE TITLE
Migrating to TypeScript

### ISSUE THREAD

**Issue by tapas4java** [auth0/angular2-authentication-sample#15]
Do you have any plan to migrate this repo to typescript or create a separate branch for typescript?

**Comment by paulvanbladel** [comment]
+1 from me :)
Would be the first serious typescript sample !

**Comment by mgonto** [comment]
I'll try to work on it later this week or next at most :).

@gdi2290 wanna help with it :)?

**Comment by mgonto** [comment]
Code will be very similar though. I'm using Types and Decorators here :).

**Comment by PatrickJS** [comment]
@mgonto if I can start off with https://github.com/angular-class/angular2-webpack-starter then yeah I totally can ;-)

**Comment by paulvanbladel** [comment]
Mhhm, never tried webpack, but when looking into the webpack config file... what's that ?
Angular seems to embrace SystemJs, so maybe something based on https://github.com/frankwallis/plugin-typescript ?

**Comment by tapas4java** [comment]
I'm too confused between SystemJS/JSPM and Webpack. JSPM looks future proof where as Webpack looks more mature and production ready at the moment.

**Comment by tapas4java** [comment]
@mgonto...Any progres on this??

**Comment by neokeats** [comment]
hi 
+1

**Comment by c1rus** [comment]
+1

**Comment by mgonto** [comment]
Migration done :). Check master!
