### ISSUE TITLE
Typings update needed - typings/angular2/angular2.d.ts still on alpha.26

### ISSUE THREAD

**Issue by NathanWalker** [auth0/angular2-authentication-sample#27]
I believe the `_custom` typings folder is confusing and troublesome. When running `tsd install` it removes the `_custom` folder and will install correct typings for the latest commit specified in tsd.json...which for angular2 is: https://github.com/borisyankov/DefinitelyTyped/commit/e29cf4cafbd804cae59dfc4cc8007560310f4520

I think the typings setup here just needs to be cleaned up and updated to help alleviate pain here?

**Comment by lBilali** [comment]
You can look at https://github.com/mgechev/angular2-seed for latest typings.
Seems like they have the ones for alpha.31

**Comment by PatrickJS** [comment]
yo @NathanWalker, I changed the typing convention to

`/src/typings/` custom typings
`/src/typings/_custom.d.s` main file to require everything
`/src/typings/tsd.d.ts` requires tsd_typings
`/tsd_typings/` tsd typings (like node_modules these files live and generates at root level)

so far this is the best approach while also reinstalling tsd_typings on each npm install. I have a friend who is working on better tsd/typing management so this works for me until he is done
https://github.com/angular-class/angular2-webpack-starter

**Comment by NathanWalker** [comment]
Thanks @gdi2290 for the suggestion :+1: That seems like a great way to go. I'll try updating this project to follow something similar.

**Comment by NathanWalker** [comment]
I've updated the PR here:
https://github.com/auth0/angular2-authentication-sample/pull/26

...see comments there for further explanation of changes. Thanks again @gdi2290 , I hope more people can follow your pattern of managing Typings, seems really clean and smart to me.

**Comment by chenkie** [comment]
Updated to beta 0
