### ISSUE TITLE
Pipe problem when running app (not app-simple) and including app.js

### ISSUE THREAD

**Issue by raptoria** [auth0/angular2-authentication-sample#29]
Error below:

Uncaught TypeError: change_detection_1.Pipes.extend is not a functionwebpackJsonp.273 @ pipes.ts:15__webpack_require__ @ bootstrap ec2d90a06f7e26d96c5f:71webpackJsonp.256 @ app.ts:21__webpack_require__ @ bootstrap ec2d90a06f7e26d96c5f:71webpackJsonp.255 @ bootstrap.ts:43__webpack_require__ @ bootstrap ec2d90a06f7e26d96c5f:71webpackJsonp.0 @ app.js:8__webpack_require__ @ bootstrap ec2d90a06f7e26d96c5f:71webpackJsonpCallback @ bootstrap ec2d90a06f7e26d96c5f:42(anonymous function) @ app.js:2
client?cd17:36 [WDS] Warnings while compiling.

**Comment by ctindel** [comment]
Pipes.append has been renamed into Pipes.extend in alpha 32.

**Comment by PatrickJS** [comment]
the repo doesn't have to include it's own `|json` Pipe anymore. If you wanted to do so then you would need to use 

``` es6
Pipes.extend({
  'somepipe': SomePipe
})
```

either the `hostInjector` or `viewInjector` in the `App` component rather than app bindings in 

``` typescript
bootstrap(app: Component, appInjector?: Array<Binding>, errorReporter?: Function): Promise
```
