### ISSUE TITLE
Run nodejs-jwt-authentication-sample and angular2-authentication-sample  in one webpack.config.js is possible? 

### ISSUE THREAD

**Issue by emirdeliz** [auth0/angular2-authentication-sample#37]
I would like to run this program in single file. I need run two ports 3000 and 3001. These be ports necessary for sample login and authentication sample.  Any sugestion?

**Comment by valorkin** [comment]
added `npm run server` in #38 
if tooo lazy to run 2 terminals use `npm run server & npm start` :)
