### ISSUE TITLE
Social Logins

### ISSUE THREAD

**Issue by drejohnson** [auth0/angular2-authentication-sample#42]
Any plans to add an example with social logins?

**Comment by examdotcom** [comment]
For Angular 1 I recommend https://github.com/sahat/satellizer
I can't see any Angular 2 activity on that project, but probably worth raising an issue with that project to upgrade to Angular 2.

**Comment by chenkie** [comment]
Auth0 handles social logins for easily :) You can see details in the [aside of this post](https://auth0.com/blog/2015/11/10/introducing-angular2-jwt-a-library-for-angular2-authentication/).

There is also an Angular 2 version of Satellizer called [ng2-ui-auth](https://github.com/ronzeidman/ng2-ui-auth).
