### ISSUE TITLE
Update to Beta7?

### ISSUE THREAD

**Issue by mikepc** [auth0/angular2-authentication-sample#57]
Trying to use this to boilerplate a new project and I wanted to use a more current version of the beta, but things went awry:
error TS2304: Cannot find name 'Promise'
error TS2304: Cannot find name 'Map'
error TS2304: Cannot find name 'Iterator'

Angular2 is in so much flux it's hard to pin down exactly what I need to do for this to run without errors. Given I'm brand new to TS and Angular2, I could use some guidance on how to clear these errors.

**Comment by chenkie** [comment]
Updated to beta 9 :)
