### ISSUE TITLE
jwt signing without password

### ISSUE THREAD

**Issue by rakeen** [auth0/angular2-authentication-sample#59]
While signing a token with [jsonwebtoken](https://github.com/auth0/angular2-authentication-sample/blob/master/backend/user-routes.js#L16) you guys omitted the password. Is there any specific reason to do so(i.e security concern)?

**Comment by chenkie** [comment]
The user's password shouldn't be a part of the JWT payload and generally you just need some identifier for the user. If passwords are properly stored (hashed) then they wouldn't be useful as part of the payload anyway :)
