### ISSUE TITLE
Bootstrapping app

### ISSUE THREAD

**Issue by Foxandxss** [auth0/angular2-authentication-sample#9]
Last issue, I promise :P

I am trying to understand the last piece of this puzzle so here I go:

``` javascript
bootstrap(App, [
  bind(Router).toValue(new RootRouter(new Pipeline())),
  bind(PipeRegistry).toValue(new PipeRegistry(pipes))
]);
```

I think that I understand the second parameter as new injections, but seems to be like new injections for the `App` component itself. How does this work? Does angular (as today) need the router to be injected in that way? And what about the Pipe stuff? I know it is to add a new "filter", but why do we need to add it in the bootstrap?

**Comment by PatrickJS** [comment]
the Router will be kinda fixed during the LocationService merge since they will export a  `routerInjectables` with the `RootRouter` instance. The same needs to be done with `PipeRegistry` but that needs to be refactored internally for Angular 2 to provide a better API for adding user added pipes. aka ignore the pipes for now

**Comment by Foxandxss** [comment]
I see, but I am more concerned about how it works.

If I understood correctly, since the router doesn't export its instance, you need to do it by hand, is that right? And the same to add new pipes.

And yeah, all the boilerplate will go away for sure.

**Comment by PatrickJS** [comment]
@Foxandxss so they are exporting `routerInjectables` which has the `RootRouter` instance. As of last night it was merged to master which means we are waiting for the next tagged release which means you can do this

``` es6
import {bootstrap, Component, View} from 'angular2/angular2';
import {routerInjectables} from 'angular2/router';

import {pipes} from './utils/pipes';

@Component({ selector: 'app' })
@View({ template: 'hello world' })
class App {}

bootstrap(App, [
  routerInjectables, // inject RootRouter instance
  bind(PipeRegistry).toValue(new PipeRegistry(pipes))
]);
```

the interface for pipes is a wip as everything else is as in usually the fix you want is in master and not in the tagged release

**Comment by Foxandxss** [comment]
I see thank you. I am writing an example with tutorial and I need to explain everything.

**Comment by PatrickJS** [comment]
Yeah np @Foxandxss, if you want a co-writer I can review and edit your tutorial but we are on the bleeding edge which means we're the ones bleeding. For example the forms aren't using ControlGroup or Control

**Comment by Foxandxss** [comment]
Sure @gdi2290. I am building the demo now. I will send you the demo link + article so you can review it before I push it to the blog.

Yeah, this is bleeding edge, but I am the admin of the IRC channel so I am always doing all the support and the poeple is starting to ask about angular 2 and I need to learn all this stuff to be able to answer.

**Comment by mgonto** [comment]
Nice :). Send me the article as well, I'll review.

Thanks for all the PRs. Now it's time to practice live coding it for the ngVegas talk :D

**Comment by Foxandxss** [comment]
np @mgonto, I am the first who wants to learn more Angular 2 and JWT is my weakness :+1: 

Te enviaré el enlace también :)

**Comment by Foxandxss** [comment]
Alright,  @mgonto && @gdi2290 I finished it all.

Repos:
https://github.com/angular-tips/GermanWords-frontend-angular-2
https://github.com/angular-tips/GermanWords-backend-koa

Article:
https://github.com/Foxandxss/angular-tips/blob/master/source/_posts/2015-05-04-an-introduction-to-angular-2.markdown

Better to read the article in raw mode :P

Since all is inside github, feel free to send PRs.

I will wait until tomorrow to publish it.
